import type { Metadata } from "next";
import PageBackground from "../../components/PageBackground";
import SiteNav from "../../components/SiteNav";

export const metadata: Metadata = {
  title: "About — Apiz",
  description: "Laravel developer based in Perak, Malaysia — background, experience, and education.",
};

const experience = [
  { organisation: "Majlis Daerah Kerian (MDK)", period: "Mar 2023 – Sep 2023", description: "Built an SSO licensing system (Elesen) in PHP/MySQL for a local government agency, including PDF generation with TCPDF and interfaces for premises registration." },
  { organisation: "Pusat Transformasi Digital (PTD), USM", period: "Oct 2025 – Jan 2026", description: "Developed AI-literacy training curriculum, delivered workshops, and redesigned the e-learning platform's WordPress backend." },
];
const education = [["Bachelor of Computer Science (Hons)", "UiTM Jasin", "Oct 2023 – Mar 2026"], ["Diploma in Computer Science", "UiTM Arau", "Mar 2021 – Sep 2023"]];
const certificates = [
  ["International Conference on Language Education (iCOLE)", "Jun 2021"],
  ["Large-Scale Electromagnetic Transient (EMT) Simulation using Simscape", "Apr 2024"],
  ["TOP CODERS — Coding Challenge 2024", "Nov 2024"],
];

export default function About() {
  return <main className="relative min-h-screen overflow-hidden"><PageBackground /><div className="relative z-10 mx-auto max-w-6xl px-6 py-8 sm:px-10 sm:py-10"><SiteNav />
    <header className="grid gap-10 border-b border-blueprint-line/80 py-16 sm:py-24 lg:grid-cols-[1.35fr_0.65fr] lg:items-end"><div><p className="mb-5 font-mono text-xs font-semibold uppercase tracking-[0.2em] text-brass">02—About</p><h1 className="max-w-3xl font-display text-5xl leading-[0.95] tracking-[-0.04em] text-[#f8fafc] sm:text-7xl">Building systems people can rely on.</h1></div><p className="border-l-2 border-brass pl-5 text-base leading-7 text-[#d8e3ea] sm:max-w-sm sm:text-lg">Full-stack Laravel developer based in Perak, Malaysia.</p></header>
    <section className="grid gap-6 border-b border-blueprint-line/80 py-14 sm:grid-cols-[72px_1fr] sm:gap-8 sm:py-20"><p className="font-mono text-xs font-semibold text-brass">01</p><p className="max-w-3xl text-lg leading-8 text-[#f8fafc] sm:text-xl">Full-stack web developer with hands-on Laravel experience across independent portfolio projects, including multi-role clinic and salon management systems with real-time scheduling, booking conflict detection, and automated notification workflows. I also bring practical experience building a production PHP/MySQL licensing system for a local government agency and delivering AI-literacy training at Universiti Sains Malaysia.</p></section>
    <section className="py-16 sm:py-24" aria-labelledby="experience-heading"><SectionTitle eyebrow="Experience" title="Where I've contributed" id="experience-heading" count="02 roles" /><div className="mt-8 border-t border-blueprint-line/80">{experience.map((role, index) => <article key={role.organisation} className="grid gap-5 border-b border-blueprint-line/80 py-8 sm:grid-cols-[72px_1fr_auto] sm:gap-8"><span className="font-mono text-xs font-semibold text-brass">{String(index + 1).padStart(2, "0")}</span><div><h3 className="font-display text-2xl tracking-[-0.02em] text-[#f8fafc]">{role.organisation}</h3><p className="mt-3 max-w-2xl leading-7 text-[#c5d4dd]">{role.description}</p></div><time className="font-mono text-xs font-medium text-[#b8cad6] sm:pt-1">{role.period}</time></article>)}</div></section>
    <section className="grid gap-10 border-t border-blueprint-line/80 py-16 sm:grid-cols-[1fr_1.2fr] sm:py-24" aria-labelledby="education-heading"><div><p className="font-mono text-xs font-semibold uppercase tracking-[0.2em] text-brass">Education</p><h2 id="education-heading" className="mt-2 font-display text-4xl tracking-[-0.03em] text-[#f8fafc]">Foundation</h2><p className="mt-4 max-w-xs text-sm leading-6 text-[#c5d4dd]">Formal training in computer science, with a focus on building useful software.</p></div><div className="overflow-hidden rounded-xl border border-blueprint-line/80 bg-blueprint/25">{education.map(([degree, school, period]) => <article key={degree} className="grid gap-2 border-b border-blueprint-line/80 px-5 py-6 last:border-b-0 sm:grid-cols-[1fr_auto]"><div><h3 className="text-lg font-semibold text-[#f8fafc]">{degree}</h3><p className="mt-1 text-[#c5d4dd]">{school}</p></div><time className="font-mono text-xs font-medium text-[#b8cad6] sm:pt-1">{period}</time></article>)}</div></section>
    <section className="grid gap-10 border-t border-blueprint-line/80 py-16 sm:grid-cols-[1fr_1.2fr] sm:py-24" aria-labelledby="certificates-heading"><div><p className="font-mono text-xs font-semibold uppercase tracking-[0.2em] text-brass">Certificates</p><h2 id="certificates-heading" className="mt-2 font-display text-4xl tracking-[-0.03em] text-[#f8fafc]">Credentials</h2><p className="mt-4 max-w-xs text-sm leading-6 text-[#c5d4dd]">Courses and challenges completed alongside coursework.</p></div><div className="overflow-hidden rounded-xl border border-blueprint-line/80 bg-blueprint/25">{certificates.map(([name, date]) => <article key={name} className="grid gap-2 border-b border-blueprint-line/80 px-5 py-6 last:border-b-0 sm:grid-cols-[1fr_auto] sm:items-center"><h3 className="text-lg font-semibold text-[#f8fafc]">{name}</h3><time className="font-mono text-xs font-medium text-[#b8cad6]">{date}</time></article>)}</div></section>
    <section className="border-t border-blueprint-line/80 py-16 sm:py-24" aria-labelledby="contact-heading"><SectionTitle eyebrow="Contact" title="Let's work together." id="contact-heading" /><div className="mt-8 grid gap-3 sm:grid-cols-3"><ContactLink href="mailto:apizisapiz@gmail.com" label="Email" text="apizisapiz@gmail.com" /><ContactLink href="https://github.com/Apiz1" label="GitHub" text="github.com/Apiz1" /><ContactLink href="https://linkedin.com/in/muhd-hafiz-644660380" label="LinkedIn" text="View profile" /></div></section>
    <footer className="flex flex-col gap-3 border-t border-blueprint-line/80 py-7 font-mono text-[11px] font-medium uppercase tracking-[0.15em] text-[#b8cad6] sm:flex-row sm:justify-between"><span>About · Contact</span><span>Laravel · PHP · PostgreSQL</span></footer>
  </div></main>;
}
function SectionTitle({ eyebrow, title, id, count }: { eyebrow: string; title: string; id: string; count?: string }) { return <div className="flex items-end justify-between gap-4"><div><p className="font-mono text-xs font-semibold uppercase tracking-[0.2em] text-brass">{eyebrow}</p><h2 id={id} className="mt-2 font-display text-4xl tracking-[-0.03em] text-[#f8fafc] sm:text-5xl">{title}</h2></div>{count && <span className="hidden font-mono text-xs font-medium text-[#b8cad6] sm:block">{count}</span>}</div>; }
function ContactLink({ href, label, text }: { href: string; label: string; text: string }) { return <a href={href} target={href.startsWith("mailto:") ? undefined : "_blank"} rel={href.startsWith("mailto:") ? undefined : "noreferrer"} className="group rounded-xl border border-blueprint-line/80 bg-blueprint/30 p-5 transition hover:border-brass/70 hover:bg-blueprint/55"><p className="font-mono text-[10px] font-semibold uppercase tracking-[0.18em] text-[#b8cad6]">{label}</p><p className="mt-3 break-all text-base font-semibold text-[#f8fafc] transition group-hover:text-brass">{text} <span aria-hidden="true">↗</span></p></a>; }
